# Generated by Django 2.2 on 2021-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
